# --- SUPABASE ---
supabase.url=jdbc:postgresql://db.uunnvixzrgntjulmxncq.supabase.co:5432/postgres
supabase.user=postgres
supabase.password=supabasepass12345.
supabase.driver=org.postgresql.Driver

# --- SQL SERVER (SQLEXPRESS) ---
sqlserver.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=registraduriadb;encrypt=true;trustServerCertificate=true
sqlserver.user=javaCliente
sqlserver.password=123
sqlserver.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver

# --- POSTGRES (Local) ---
pglocal.url=jdbc:postgresql://localhost:5432/dbregistraduria
pglocal.user=postgres
pglocal.password=pass
pglocal.driver=org.postgresql.Driver

# --- SQLITE ---
sqlite.url=jdbc:sqlite:./registraduriaSQLite.db
sqlite.driver=org.sqlite.JDBC

# --- H2 (En memoria o archivo) ---
h2.url=jdbc:h2:./registraduriaH2;AUTO_SERVER=TRUE
h2.user=sa
h2.password=
h2.driver=org.h2.Driver