# reCAPTCHA v2 - Obtener en https://www.google.com/recaptcha/admin
# Claves de TEST (siempre pasan):
recaptcha.site.key=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
recaptcha.secret.key=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
recaptcha.enabled=true